spring:
  profiles:
    active: test
  application:
    name: goods_catalogue_service
server:
  port: 8000
kafka:
  configuration:
    bootstrapServers: localhost:9092
    recomendations:
      sampling: 100
      topic: recomendations-topic
services:
  recomendations:
    url: http://localhost:8001